- name: Base Linux configuration
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    username: "{{ lookup('env','USERNAME') }}"

  tasks:
    # cpu architecture
    - name: Get CPU architecture
      shell: dpkg --print-architecture
      register: dpkg_architecture_command
      changed_when: false
    
    - name: Store CPU architecture
      set_fact:
        dpkg_architecture: "{{ dpkg_architecture_command.stdout }}"

    # os version
    - name: Get OS version
      shell: lsb_release -cs
      register: lsb_release_command
      changed_when: false
    
    - name: Store OS version
      set_fact:
        lsb_release: "{{ lsb_release_command.stdout }}"

    # base packages
    - name: Install base packages
      apt:
        name:
          - apt-file
          - apt-transport-https
          - bat
          - build-essential
          - ca-certificates
          - cmake
          - curl
          - fd-find
          - fzf
          - git
          - git-gui
          - gnupg2
          - httpie
          - jq
          - neovim
          - netcat
          - net-tools
          - python3-pip
          # TODO: Reenable when installation bug is fixed
          #   See https://bugs.launchpad.net/ubuntu/+source/rust-bat/+bug/1868517
          # - ripgrep
          - software-properties-common
          - tree
          - unzip
          - wget
          - zip
        state: latest
        force: yes

    # os config
    - name: Set timezone
      timezone:
        name: Australia/Sydney
    
    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL) NOPASSWD: ALL"
        validate: visudo -cf %s
    
    - name: Disable screen lock
      become: yes
      become_user: "{{ username }}"
      shell: "gsettings set org.gnome.desktop.screensaver lock-enabled false"
    
    - name: Disable screensaver
      become: yes
      become_user: "{{ username }}"
      shell: "gsettings set org.gnome.desktop.session idle-delay 0"

    - name: Configure local profile
      become: yes
      become_user: "{{ username }}"
      copy:
        src: home/
        dest: ~/

    - name: Disable wayland
      lineinfile:
        path: /etc/gdm3/custom.conf
        regexp: "^#?WaylandEnable="
        line: "WaylandEnable=false"

    - name: Configure bash prompt
      become: yes
      become_user: "{{ username }}"
      blockinfile:
        path: ~/.bashrc
        block: |
          format_git_branch() {
            git_branch=$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')

            if [[ "${git_branch}" != "" ]]; then
              printf "\001\e[00m\002:\001\e[91m\002${git_branch}\001\e[00m\002"
            fi
          }

          export PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(format_git_branch)\$ '

    # aws cli
    - name: Install aws cli
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install
        rm -rf aws awscliv2.zip
      args:
        creates: /usr/local/bin/aws
        warn: no

    - name: Install AWS tooling
      become: yes
      become_user: "{{ username }}"
      pip:
        name:
          - awscli-local
          - awslogs
          - cfn-flip
          - cfn-lint
          - sceptre
        state: latest
        extra_args: --user

    # chromium
    - name: Install chromium
      snap:
        name: chromium

    # docker
    - name: Install docker apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
    
    - name: Add docker apt repository
      apt_repository:
        repo: "deb [arch={{ dpkg_architecture }}] https://download.docker.com/linux/ubuntu {{ lsb_release }} edge"
        filename: docker
        state: present
      notify:
        - Update apt cache
    
    - meta: flush_handlers
    
    - name: Install docker
      apt:
        name: "docker-ce:{{ dpkg_architecture }}"
        state: latest

    - name: Add user to the docker group
      user:
        name: "{{ username }}"
        groups: docker
        append: yes
    
    - name: Install docker python package
      become: yes
      become_user: "{{ username }}"
      pip:
        name: docker
        state: latest
        extra_args: --user

    # docker-compose
    - name: Install docker compose
      become: yes
      become_user: "{{ username }}"
      pip:
        name: docker-compose
        state: latest
        extra_args: --user

    # dotnet core
    - name: Install microsoft apt key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
    
    - name: Add microsoft-ubuntu apt repository
      apt_repository:
        repo: "deb [arch={{ dpkg_architecture }}] https://packages.microsoft.com/repos/microsoft-ubuntu-{{ lsb_release }}-prod {{ lsb_release }} main"
        filename: dotnetdev
        state: present
      notify:
        - Update apt cache
    
    - meta: flush_handlers
    
    - name: Install dotnet-sdk-3.1
      apt:
        name: dotnet-sdk-3.1
        state: latest

    # gh (GitHub cli)
    - name: Check latest gh version
      shell: curl -s https://api.github.com/repos/cli/cli/releases/latest | jq -r .html_url
      register: gh_latest_version
      args:
        warn: no
      changed_when: false

    - name: Check current gh version
      shell: gh --version | grep /tag/ || true
      register: gh_current_version
      args:
        warn: no
      changed_when: false

    - name: Install gh
      when: gh_latest_version.stdout != gh_current_version.stdout
      shell: |
        DOWNLOAD_URL=$( \
          curl -s https://api.github.com/repos/cli/cli/releases/latest \
          | jq -r '.assets[].browser_download_url' \
          | grep "gh_.*_linux_amd64\\.deb" \
        )
        FILE_NAME=$(basename ${DOWNLOAD_URL})

        curl -O -L ${DOWNLOAD_URL}
        apt install ./${FILE_NAME}
        rm -rf ${FILE_NAME}
      args:
        warn: no

    # jetbrains
    - name: Install Jetbrains Rider
      snap:
        name: rider
        classic: yes

    - name: Install Pycharm Professional
      snap:
        name: pycharm-professional
        classic: yes

    - name: Install IntelliJ Idea Ultimate
      snap:
        name: intellij-idea-ultimate
        classic: yes

    - name: Install DataGrip
      snap:
        name: datagrip
        classic: yes

    # nodejs
    - name: Install nvm
      become: yes
      become_user: "{{ username }}"
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      args:
        creates: ~/.nvm/nvm.sh
        warn: no

    - name: Install node
      become: yes
      become_user: "{{ username }}"
      shell: >
        bash -c "source ~/.nvm/nvm.sh && nvm install --lts --latest-npm"
      args:
        creates: ~/.nvm/alias

    # postman
    - name: Install Postman
      snap:
        name: postman

    # python
    - name: Install pipenv
      become: yes
      become_user: "{{ username }}"
      pip:
        name: pipenv
        state: latest
        extra_args: --user

    # saml2aws
    - name: Check latest saml2aws version
      shell: curl -s https://api.github.com/repos/Versent/saml2aws/releases/latest | jq -r .tag_name | sed s/^v//
      register: saml2aws_latest_version
      args:
        warn: no
      changed_when: false

    - name: Check current saml2aws version
      become: yes
      become_user: "{{ username }}"
      shell: saml2aws --version 2>&1 || true
      register: saml2aws_current_version
      args:
        warn: no
      changed_when: false

    - name: Install saml2aws
      when: saml2aws_latest_version.stdout != saml2aws_current_version.stdout
      become: yes
      become_user: "{{ username }}"
      shell: |
        DOWNLOAD_URL=$( \
          curl -s https://api.github.com/repos/Versent/saml2aws/releases/latest \
          | jq -r '.assets[].browser_download_url' \
          | grep "saml2aws_.*_linux_amd64\\.tar\\.gz" \
        )
        FILE_NAME=$(basename ${DOWNLOAD_URL})

        curl -O -L ${DOWNLOAD_URL}
        rm -f ~/.local/bin/saml2aws
        tar -xzvf ${FILE_NAME} -C ~/.local/bin
        chmod u+x ~/.local/bin/saml2aws
        rm -f ${FILE_NAME}
      args:
        warn: no

    # sqsmover
    - name: Check latest sqsmover version
      shell: curl -s https://api.github.com/repos/mercury2269/sqsmover/releases/latest | jq -r .tag_name | sed s/^v//
      register: sqsmover_latest_version
      args:
        warn: no
      changed_when: false

    - name: Check current sqsmover version
      become: yes
      become_user: "{{ username }}"
      shell: sqsmover --version 2>&1 | grep version | sed -E 's/version:\s+//' || true
      register: sqsmover_current_version
      args:
        warn: no
      changed_when: false

    - name: Install sqsmover
      when: sqsmover_latest_version.stdout != sqsmover_current_version.stdout
      become: yes
      become_user: "{{ username }}"
      shell: |
        DOWNLOAD_URL=$( \
          curl -s https://api.github.com/repos/mercury2269/sqsmover/releases/latest \
          | jq -r '.assets[].browser_download_url' \
          | grep "sqsmover_Linux_x86_64\\.tar\\.gz" \
        )
        FILE_NAME=$(basename ${DOWNLOAD_URL})

        curl -O -L ${DOWNLOAD_URL}
        rm -f ~/.local/bin/sqsmover
        tar -xzvf ${FILE_NAME} -C ~/.local/bin
        chmod u+x ~/.local/bin/sqsmover
        rm -f ${FILE_NAME}
      args:
        warn: no

    # vscode
    - name: Install vscode
      snap:
        name: code
        classic: yes

    # yarn
    - name: Uninstall cmdtest
      apt:
        name: cmdtest
        state: absent
    
    - name: Install yarn apt key
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
    
    - name: Add yarn apt repository
      apt_repository:
        repo: "deb https://dl.yarnpkg.com/debian/ stable main"
        filename: yarn
        state: present
      notify:
        - Update apt cache
    
    - meta: flush_handlers
    
    - name: Install yarn
      apt:
        name: yarn
        state: latest
        install_recommends: no

    # cleanup
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

  # handlers
  handlers:
    - name: Update apt cache
      apt:
        update_cache: yes
