- name: GIS development software
  hosts: 127.0.0.1
  connection: local

  tasks:
    # qgis
    - name: Install qgis apt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: F7E06F06199EF2F2

    - name: Add qgis apt repository
      apt_repository:
        repo: "deb https://qgis.org/ubuntu {{ ansible_facts['distribution_release'] }} main"
        filename: qgis
        state: present
        update_cache: yes

    - name: Install qgis
      apt:
        name:
          - qgis
          - qgis-plugin-grass
        state: latest

    # gpsbabel
    - name: Install gpsbabel
      apt:
        name:
          - gpsbabel
          - gpsbabel-gui
          - gpsbabel-doc
        state: latest

    # gps editors
    - name: Install GPS editors
      apt:
        name:
          - gpsprune
          - pytrainer
          - qmapshack
          - viking

    # cleanup
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
