- name: User profile setup
  hosts: 127.0.0.1
  connection: local

  tasks:
    # profile
    - name: Configure local profile
      copy:
        src: home/
        dest: ~/

    - name: Copy skeleton files
      copy:
        src: skel/
        dest: ~/
        force: no

    # aws cli tools
    - name: Install AWS tooling
      pip:
        name:
          - awscli-local
          - awslogs
          - cfn-flip
          - cfn-lint
        state: latest
        extra_args: --user

    # docker
    - name: Install docker python package
      pip:
        name: docker
        state: latest
        extra_args: --user

    # docker-compose
    - name: Install docker compose
      pip:
        name: docker-compose
        state: latest
        extra_args: --user

    # nodejs
    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
      args:
        creates: ~/.nvm/nvm.sh
        warn: no

    - name: Install node
      shell: >
        bash -c "source ~/.nvm/nvm.sh && nvm install --lts --latest-npm"
      args:
        creates: ~/.nvm/alias

    - name: Install yarn
      shell: >
        bash -c "source ~/.nvm/nvm.sh && npm install --global yarn"

    - name: Install npm-check-updates
      shell: >
        bash -c "source ~/.nvm/nvm.sh && npm install --global npm-check-updates"

    # pwsh
    - name: Install pwsh modules
      shell: |
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-Module posh-git, Terminal-Icons
      args:
        executable: /usr/bin/pwsh

    # python
    - name: Install pipenv
      pip:
        name: pipenv
        state: latest
        extra_args: --user

    # shell prompt
    - name: Configure bash to use oh-my-posh
      lineinfile:
        path: ~/.bashrc
        line: eval "$(oh-my-posh init bash --config ~/.poshthemes/devvm.omp.json)"
