- name: Docker - User
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add user to the docker group
      when: is_desktop | bool
      become: yes
      ansible.builtin.user:
        name: "{{ ansible_facts['user_id'] }}"
        groups: docker
        append: yes
