- name: Git - System
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Check latest gcm version
      ansible.builtin.shell: curl -s https://api.github.com/repos/git-ecosystem/git-credential-manager/releases/latest | jq -r .tag_name | sed 's/^v//'
      register: gcm_latest_version
      changed_when: false

    - name: Check current gcm version
      ansible.builtin.shell: git-credential-manager --version | sed 's/\+.*//' || true
      register: gcm_current_version
      changed_when: false

    - name: Install gcm
      when:
        - is_desktop | bool
        - gcm_latest_version.stdout != gcm_current_version.stdout
      ansible.builtin.shell: |
        DOWNLOAD_URL=$( \
          curl -s curl -s https://api.github.com/repos/git-ecosystem/git-credential-manager/releases/latest \
          | jq -r '.assets[].browser_download_url' \
          | grep "gcm-linux_amd64\\..*\\.deb" \
        )
        FILE_NAME=$(basename ${DOWNLOAD_URL})

        curl -O -L ${DOWNLOAD_URL}
        apt install ./${FILE_NAME}
        rm -rf ${FILE_NAME}
