- name: HashiCorp - System
  hosts: 127.0.0.1
  connection: local

  vars:
    hashicorp_gpg_key_path: /usr/share/keyrings/hashicorp-archive-keyring.gpg

  tasks:
    - name: Download hashicorp apt key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: "{{ hashicorp_gpg_key_path }}.key"

    - name: Unarmour hashicorp apt key
      ansible.builtin.shell: |
        cat {{ hashicorp_gpg_key_path }}.key | gpg --dearmor > {{ hashicorp_gpg_key_path }}
      args:
        creates: "{{ hashicorp_gpg_key_path }}"

    - name: Add hashicorp apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ hashicorp_gpg_key_path }}] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
        filename: hashicorp
        state: present
        update_cache: yes

    - name: Install packages
      ansible.builtin.apt:
        name:
          - packer
          - terraform
        state: latest
