# ==================================================
#  Shared PowerShell Profile
#
#    Do not edit this file!!
#    Instead add local override scripts to
#    $($PROFILE.CurrentUserAllHosts)/local
# ==================================================

$PSProfile = $PROFILE.CurrentUserAllHosts
function Open-PwshProfile {
  code (Split-Path $PSProfile)
}
Set-Alias profile Open-PwshProfile

# Import profile helpers
$ProfileHelpersPath = "$PSScriptRoot/profile"
if (Test-Path $ProfileHelpersPath -PathType Container) {
  Get-ChildItem $ProfileHelpersPath | % { . $_ }
}

# Import local overrides
$LocalProfileOverridesPath = "$PSScriptRoot/local"
if (Test-Path $LocalProfileOverridesPath -PathType Container) {
  Get-ChildItem $LocalProfileOverridesPath | % { . $_ }
}
